import type { CardId, TurnPhase } from '../types.js';

export interface CardDefinition {
  id: CardId;
  name: string;
  points: number;
  unique: boolean;
  image: string;
  description: string;
  timing: Array<TurnPhase | 'afterOpponentMove' | 'afterOpponentCard'>;
  continuing: boolean;
}

export const CARD_CATALOG: Record<CardId, CardDefinition> = {
  blessing: {
    id: 'blessing',
    name: 'Blessing',
    points: 6,
    unique: false,
    image: '/KC9_card4.png',
    description: 'On this move, any one of your pieces may move any distance diagonally, as though it were a Bishop. You cannot capture with this move.',
    timing: ['beforeMove'],
    continuing: false,
  },
  vulture: {
    id: 'vulture',
    name: 'Vulture',
    points: 5,
    unique: false,
    image: '/KC9_card3.png',
    description: 'Take the last card played by your opponent and put it in your hand. If each player has his own deck of cards, you must also discard your top undrawn card.',
    timing: ['afterOpponentCard'],
    continuing: false,
  },
  truce: {
    id: 'truce',
    name: 'Truce',
    points: 5,
    unique: false,
    image: '/KC9_card2.png',
    description: 'Capture is now forbidden. This effect lasts until a King is in check or a stalemate occurs. If a stalemate occurs, discard this card and start counting moves again for the purpose of determining stalemate.',
    timing: ['afterMove'],
    continuing: true,
  },
  'forbidden-city': {
    id: 'forbidden-city',
    name: 'Forbidden City',
    points: 5,
    unique: false,
    image: '/KC7_card3.png',
    description:
      'Place a marker in any unoccupied square. No pieces can enter this square, or pass through it, for the rest of the game. Knights and other "jumping" pieces may still pass over it.',
    timing: ['afterMove'],
    continuing: true,
  },
  confabulation: {
    id: 'confabulation',
    name: 'Confabulation',
    points: 5,
    unique: false,
    image: '/KC7_card4.png',
    description:
      'Make a legal move which puts two of your pieces (other than Kings) on the same square. These two pieces "merge" into a new piece. It can move, capture, and be affected by cards like either one of them. Move the two pieces together. Confabulated Pawns cannot promote.',
    timing: ['beforeMove'],
    continuing: true,
  },
  ghostwalk: {
    id: 'ghostwalk',
    name: 'Ghostwalk',
    points: 5,
    unique: false,
    image: '/KC8_card1.png',
    description:
      'On this move, one of your pieces gains the ability to pass through your own pieces. It may not pass through enemy pieces, and must end its move on an empty square, without capturing. Its move must be otherwise legal.',
    timing: ['beforeMove'],
    continuing: false,
  },
  'irresistible-force': {
    id: 'irresistible-force',
    name: 'Irresistible Force',
    points: 5,
    unique: false,
    image: '/KC8_card2.png',
    description:
      'Move one of your Pawns to the occupied square in front of it, by pushing the piece occupying that square to the next square. If that square is occupied, the piece there is pushed to the next square, and so on. If a piece is pushed from the last rank off the chessboard, it is taken! A King cannot be pushed.',
    timing: ['beforeMove'],
    continuing: false,
  },
  masquerade: {
    id: 'masquerade',
    name: 'Masquerade',
    points: 5,
    unique: false,
    image: '/KC8_card3.png',
    description:
      'Move one of your pieces, except a Pawn, as if it were a Queen. You cannot capture a piece with this move.',
    timing: ['beforeMove'],
    continuing: false,
  },
  assassin: {
    id: 'assassin',
    name: 'Assassin',
    points: 2,
    unique: false,
    image: '/KC1_card1.png',
    description: 'Move one of your pieces and capture another of your own pieces with it.',
    timing: ['beforeMove'],
    continuing: false,
  },
  disintegration: {
    id: 'disintegration',
    name: 'Disintegration',
    points: 2,
    unique: false,
    image: '/KC1_card2.png',
    description:
      'Remove one of your own Pawns from the chessboard, and set it aside. It is now *dead*, and cannot be brought back into play with another card.',
    timing: ['beforeMove', 'afterMove'],
    continuing: false,
  },
  doomsayer: {
    id: 'doomsayer',
    name: 'Doomsayer',
    points: 2,
    unique: false,
    image: '/KC1_card3.png',
    description:
      'The next player who pronounces the name of a piece, except "King," loses one piece of that type. If he doesn\'t own a piece of that type, this card remains in effect. When you play this card, your opponent has the option to name a piece immediately.',
    timing: ['afterMove'],
    continuing: true,
  },
  fanatic: {
    id: 'fanatic',
    name: 'Fanatic',
    points: 2,
    unique: false,
    image: '/KC1_card4.png',
    description:
      'Move one of your Pawns forward three squares, provided the path is clear. It may not capture on this move, or be captured *en passant*.',
    timing: ['beforeMove'],
    continuing: false,
  },
  annexation: {
    id: 'annexation',
    name: 'Annexation',
    points: 3,
    unique: false,
    image: '/KC2_card1.png',
    description:
      'Move one or two of your Pawns forward, two squares each. Neither one may make a capture. A Pawn which was on its starting square may still be captured *en passant* after this move, if an enemy Pawn is in position to do so.',
    timing: ['beforeMove'],
    continuing: false,
  },
  'forced-march': {
    id: 'forced-march',
    name: 'Forced March',
    points: 3,
    unique: false,
    image: '/KC2_card2.png',
    description: 'Move one or two of your Pawns sideways, in either direction, one square each.',
    timing: ['beforeMove'],
    continuing: false,
  },
  guardian: {
    id: 'guardian',
    name: 'Guardian',
    points: 3,
    unique: true,
    image: '/KC2_card3.png',
    description:
      'Move one of your Pawns forward (you may move two squares if it the Pawn is second rank). Your piece which was just behind the Pawn may follow, so it remains directly behind. Your Pawn is thus protected from capture *en passant*. Play this card on your move, instead of making a regular move.',
    timing: ['beforeMove'],
    continuing: false,
  },
  heresy: {
    id: 'heresy',
    name: 'Heresy',
    points: 3,
    unique: false,
    image: '/KC2_card4.png',
    description:
      'Each Bishop that can do so must be moved to an adjacent empty square by its owner, thus changing the color of the squares it moves on. Your opponent must move his Bishops first.',
    timing: ['afterMove'],
    continuing: false,
  },
  cowardice: {
    id: 'cowardice',
    name: 'Cowardice',
    points: 4,
    unique: false,
    image: '/KC4_card3.png',
    description:
      "Move one of your opponent's Pawns one or two squares backward. It may not enter or cross an occupied square.",
    timing: ['afterMove'],
    continuing: false,
  },
  doppelganger: {
    id: 'doppelganger',
    name: 'Doppelganger',
    points: 4,
    unique: false,
    image: '/KC4_card4.png',
    description:
      'Move one of your pieces (except a Pawn) as if it were a piece of the same kind as the one your opponent has just moved. You cannot capture a piece with this move.',
    timing: ['beforeMove'],
    continuing: false,
  },
  rebirth: {
    id: 'rebirth',
    name: 'Rebirth',
    points: 4,
    unique: true,
    image: '/KC6_card1.png',
    description:
      'Move one enemy piece to any square it could have occupied at the beginning of the game. The square must be empty or contain one of your pieces. If one of your pieces is in the square, it is captured.',
    timing: ['afterMove'],
    continuing: false,
  },
  revenge: {
    id: 'revenge',
    name: 'Revenge',
    points: 4,
    unique: false,
    image: '/KC6_card2.png',
    description: "Remove one of your opponent's Pawns from the chessboard. It is regarded as captured.",
    timing: ['afterOpponentMove'],
    continuing: false,
  },
  toll: {
    id: 'toll',
    name: 'Toll',
    points: 4,
    unique: false,
    image: '/KC6_card3.png',
    description:
      'Play this card when your opponent has just moved a piece toward you across the "frontier" - the line separating your half of the board from his. He must "pay" by choosing a Pawn to lose. If he does not wish to pay, his turn is canceled. He gets back any card he used, but he cannot make another move.',
    timing: ['afterOpponentMove'],
    continuing: false,
  },
  bog: {
    id: 'bog',
    name: 'Bog',
    points: 4,
    unique: false,
    image: '/KC4_card2.png',
    description:
      "Play this card after your opponent moves a Rook, Bishop or Queen two squares or more. His piece cannot make the planned move; it stops after moving one square in the chosen direction.",
    timing: ['afterOpponentMove'],
    continuing: false,
  },
  'holy-war': {
    id: 'holy-war',
    name: 'Holy War',
    points: 3,
    unique: false,
    image: '/KC3_card1.png',
    description: 'Swap the positions of one of your Knights and one of your Bishops.',
    timing: ['afterMove'],
    continuing: false,
  },
  madman: {
    id: 'madman',
    name: 'Madman',
    points: 3,
    unique: false,
    image: '/KC3_card2.png',
    description:
      'For this move, one of your pawns can move like a King in a game of checkers, by jumping diagonally over pieces from either side. It may make as many jumps as it can, in any direction. However, the pieces it jumps are not captured.',
    timing: ['beforeMove'],
    continuing: false,
  },
  pacifism: {
    id: 'pacifism',
    name: 'Pacifism',
    points: 3,
    unique: false,
    image: '/KC3_card3.png',
    description:
      'One of your pieces, except your King, becomes non-violent for the rest of the game. Place a marker on it. It can no longer capture another piece, nor may it be captured.',
    timing: ['beforeMove'],
    continuing: true,
  },
  vendetta: {
    id: 'vendetta',
    name: 'Vendetta',
    points: 3,
    unique: true,
    image: '/KC4_card1.png',
    description:
      "Each player must now use his move to capture one of his opponent's pieces, if he can do so. This effect lasts until one of the players cannot make a capture. You are not required to play a card to make a capture, even if you have a card that would let you capture.",
    timing: ['afterMove'],
    continuing: true,
  },
  anathema: {
    id: 'anathema',
    name: 'Anathema',
    points: 5,
    unique: false,
    image: '/KC6_card4.png',
    description: 'Swap the positions of a Bishop and a Rook belonging to your opponent.',
    timing: ['afterMove'],
    continuing: false,
  },
  crab: {
    id: 'crab',
    name: 'Crab',
    points: 5,
    unique: false,
    image: '/KC7_card1.png',
    description:
      'One of your Pawns becomes a Crab for the rest of the game. Place a marker underneath it as a reminder. A Crab moves and captures diagonally, like a Bishop, but only forward and only one square at a time. If a Crab reaches the last rank, it is promoted like a regular Pawn.',
    timing: ['afterMove'],
    continuing: true,
  },
  'dark-mirror': {
    id: 'dark-mirror',
    name: 'Dark Mirror',
    points: 5,
    unique: false,
    image: '/KC7_card2.png',
    description:
      'On this move, one of your Pawns can capture by moving diagonally backward instead of forward.',
    timing: ['beforeMove'],
    continuing: false,
  },
  breakthrough: {
    id: 'breakthrough',
    name: 'Breakthrough',
    points: 6,
    unique: false,
    image: '/KC10_card1.png',
    description: 'On this move, one of your Pawns can capture by moving forward. It cannot move forward unless it captures. If for any reason this Pawn could already capture by a forward move, this card lets it capture with a diagonal move instead.',
    timing: ['beforeMove'],
    continuing: false,
  },
  evangelists: {
    id: 'evangelists',
    name: 'Evangelists',
    points: 6,
    unique: false,
    image: '/KC11_card2.png',
    description: "Swap the positions of one of your Bishops and one of your opponent's Bishops.",
    timing: ['beforeMove'],
    continuing: false,
  },
  tournament: {
    id: 'tournament',
    name: 'Tournament',
    points: 6,
    unique: false,
    image: '/KC12_card3.png',
    description: "Swap the positions of one of your Knights and one of your opponent's Knights.",
    timing: ['beforeMove'],
    continuing: false,
  },
  cathedral: {
    id: 'cathedral',
    name: 'Cathedral',
    points: 7,
    unique: false,
    image: '/KC13_card2.png',
    description: 'Swap the positions of one of your Rooks and one of your Bishops.',
    timing: ['afterMove'],
    continuing: false,
  },
  'lost-castle': {
    id: 'lost-castle',
    name: 'Lost Castle',
    points: 7,
    unique: false,
    image: '/KC14_card3.png',
    description: "Swap the positions of one of your Rooks and one of your opponent's Rooks.",
    timing: ['beforeMove'],
    continuing: false,
  },
  siege: {
    id: 'siege',
    name: 'Siege',
    points: 7,
    unique: false,
    image: '/KC15_card1.png',
    description: 'Swap the positions of one of your Knights and one of your Rooks.',
    timing: ['afterMove'],
    continuing: false,
  },
  'holy-quest': {
    id: 'holy-quest',
    name: 'Holy Quest',
    points: 7,
    unique: false,
    image: '/KC14_card1.png',
    description: 'Swap the positions of a Bishop and a Knight belonging to your opponent.',
    timing: ['afterMove'],
    continuing: false,
  },
  treason: {
    id: 'treason',
    name: 'Treason',
    points: 8,
    unique: false,
    image: '/KC17_card1.png',
    description: 'Swap the positions of a Rook and a Knight belonging to your opponent.',
    timing: ['afterMove'],
    continuing: false,
  },
  onslaught: {
    id: 'onslaught',
    name: 'Onslaught',
    points: 6,
    unique: false,
    image: '/KC12_card1.png',
    description:
      'Any number of your Pawns which can legally move may all move one square forward. None of them may make a capture.',
    timing: ['beforeMove'],
    continuing: false,
  },
  'long-jump': {
    id: 'long-jump',
    name: 'Long Jump',
    points: 7,
    unique: false,
    image: '/KC14_card2.png',
    description:
      'Move one of your Knights to any square whose color is different from the one it currently occupies. You cannot capture a piece with this move.',
    timing: ['beforeMove'],
    continuing: false,
  },
  dubbing: {
    id: 'dubbing',
    name: 'Dubbing',
    points: 4,
    unique: false,
    image: '/KC5_card1.png',
    description:
      'For this turn, one of your pieces may move as if it were a Knight. You cannot capture a piece with this move.',
    timing: ['beforeMove'],
    continuing: false,
  },
  earthquake: {
    id: 'earthquake',
    name: 'Earthquake',
    points: 4,
    unique: false,
    image: '/KC5_card2.png',
    description:
      'Turn the chessboard 90 degrees in any direction. Pawns move away from their owner, any in the new last rank is promoted, your opponent promoting first. Pawns in the first rank can move one or two squares forward. If undone, the rotation is reversed with the same rules.',
    timing: ['afterMove'],
    continuing: true,
  },
  'figure-dance': {
    id: 'figure-dance',
    name: 'Figure Dance',
    points: 4,
    unique: false,
    image: '/KC5_card3.png',
    description:
      'Move every piece on a corner square one corner counterclockwise. Pawns reaching their last rank are promoted.',
    timing: ['afterMove'],
    continuing: false,
  },
  'squaring-the-circle': {
    id: 'squaring-the-circle',
    name: 'Squaring the Circle',
    points: 3,
    unique: false,
    image: '/KC3_card4.png',
    description:
      'You may play this Card Only when three of the four corners of the chessboard are occupied. Move any one of your pieces to the empty corner.',
    timing: ['beforeMove'],
    continuing: false,
  },
  'no-quarter': {
    id: 'no-quarter',
    name: 'No Quarter',
    points: 4,
    unique: false,
    image: '/KC5_card4.png',
    description:
      'Play this card after you capture any enemy piece without using a card. The captured piece is now dead and cannot be brought back into play with another card.',
    timing: ['afterMove'],
    continuing: false,
  },
  panic: {
    id: 'panic',
    name: 'Panic',
    points: 5,
    unique: false,
    image: '/KC8_card4.png',
    description:
      'Your opponent has 15 seconds to make his next move. If he has not moved within this time, he loses his turn.',
    timing: ['afterMove'],
    continuing: false,
  },
  'peace-talks': {
    id: 'peace-talks',
    name: 'Peace Talks',
    points: 5,
    unique: false,
    image: '/KC9_card1.png',
    description:
      'Remove any one "continuing effect" card from play, placing it in the owner\'s discard pile. The effect of that card is immediately cancelled. If any piece is left in an illegal situation, its owner must correct the problem on his next move or lose that piece.',
    timing: ['afterMove'],
    continuing: false,
  },
};
